### PR TITLE
External review

### PR DESCRIPTION
**Pull request by Abdessittir**
Hi, in this PR I created with my coding partner a movie application that meets all the requirements from [the project](https://github.com/Abdessittir/JavaScript-capstone/projects/1).

You can find the live link in the readme file

Cheer :)

### CODE REVIEW

**Review by frank1738 — CHANGES_REQUESTED** [review]
Hi Team, 

Wonderful job so far!
There are some issues that you still need to work on to prepare your project for the assessment but you are almost there!



## Highlights

✅ Correct use of Gitflow
✅ No linter error
✅ App is designed as expected 👍 
✅ All tests are passing 👍 
✅ App is working as expected👍 


## Suggested changes

- [ ] Kindly record a five-minute video  containing :
 - A description of the project.
- A demo of the project features.
- You should also highlight some interesting piece of code or something you built that you are very proud of.
- You all should appear in the video and talk about the project.


You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by yonas44** [comment]
Thank you for your feedback @frank1738, we have implemented the changes!🙏

**Review by Abenezer-Tilahun — APPROVED** [review]
Hi @Abdessittir  @yonas44  🙋‍♂️,

- [ ] In my opinion, your project is ready for the presentation! There is nothing else to say other than... it's time to merge it :shipit:

    

- [ ] Great job implementing the changes provided by the previous reviewers 💯🎉
https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966
Good luck! 🎉

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by Abdessittir** [comment]
Thank you @Abenezer-Tilahun for the feedback 👍

**Pull request merged**
